# use api version 1 from kubernetes
apiVersion: v1
# we use Secret for storing sensitive information
kind: Secret
# specify metadata for Secret
metadata:
  name: mongo-secret
# define the data inside this resource as an arbitary
type: Opaque
# add our sensitive info under data
data:
  MONGO_ROOT_USERNAME: YWRtaW51c2Vy
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=